### PR TITLE
Add meta data if query params exists

### PR DESCRIPTION
**Pull request by Nazeeh21**
I've added the metadata if there are query params in the URL.

I've used the `react-helmet` library to add metadata. I wasn't able to test it though because it didn't overwrite the metadata from `_document.tsx`. 

Please review this and suggest the required changes.

### CODE REVIEW

**Comment by sidcode** [comment]
LGTM, will approve and merge once @Cali93 goes through it as well!

**Comment by Cali93** [comment]
Hey @Nazeeh21 I think that it would be more appropriate to use the Next head compononent
 https://nextjs.org/docs/api-reference/next/head

**Review by Cali93 — CHANGES_REQUESTED** [review]
Hey @Nazeeh21, could you give a try using this approach instead ?
https://nextjs.org/docs/api-reference/next/head

**Comment by Nazeeh21** [comment]
@Cali93 I tried that but `<Head>` component cant be used in files other than `_document.tsx` and I want to use it `index.tsx`.  Though I'll try getting the query params in `_document.tsx` and update the metadata in `_document.tsx` itself using `<Head>` from nextjs.

**Comment by Nazeeh21** [comment]
@Cali93 I've replaced the `<Helmet>` with `<Head>` from **Nextjs**. Please have a look and provide suggestions. 😃

**Comment by Nazeeh21** [comment]
Alright! workflows seem to be happy now. 😅 
@Cali93 Please have a look at the content inside the `Head` tag in `index.tsx` and if you feel to replace something or update something, please LMK. Thanks.

**Review by Cali93 — APPROVED** [review]

**Pull request merged**
